baseURL = "/"
languageCode = "en-us"
title = "e-Portfolio"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Cameron Wang"
    description = "An Online Portfolio To Display My Work."
    githubUsername = "#pseudoptics"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about-me/"
    name = "About Me"
    weight = 2
	
[[menu.main]]
    url = "/investment_v2/"
    name = "Self Investment"
    weight = 3
	
[[menu.main]]
    url = "/smart_goals/"
    name = "SMART Goals"
    weight = 4

[[menu.main]]
    url = "/employability/"
    name = "Employability"
    weight = 5
	
[[menu.main]]
    url = "/slo/"
    name = "SLOs"
    weight = 6
	
[[menu.main]]
    url = "/post/"
    name = "Learning Journal"
    weight = 7
	
[[menu.main]]
    url = "https://drive.google.com/open?id=1UO3a26I6h7SZOaMtOgLqfSYn6SVD7y68"
    name = "Resume"
    weight = 8
	
[[menu.main]]
    url = "/contact/"
    name = "Contact Me"
    weight = 9
	
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:cameronwang2000@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/pseudoptics"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/cameron-wang-a8a772150/"
    name = "linkedin"
    weight = 3
	
[[menu.icon]]
	url = "https://pseudoptics.me"
	name = "square"
	weight = 5
